const ActionType = Object.freeze({
  SET_PLAYERS: 'SET_PLAYERS',
  SET_PLAYER_SWAPS: 'SET_PLAYER_SWAPS',
  SET_TEAMS: 'SET_TEAMS',
  SET_TEAM_SWAPS: 'SET_TEAM_SWAPS',
  SET_IS_LOADING: 'SET_IS_LOADING',
  EDIT_PLAYER: 'EDIT_PLAYER',
  SAVE_PLAYER: 'SAVE_PLAYER',
  CLOSE_EDIT_MODAL: 'CLOSE_EDIT_MODAL'
});

export default ActionType;
